# Generated by Django 4.1.13 on 2026-03-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_company_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pricing_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium'), ('elite', 'Elite')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='tokens_remaining',
            field=models.IntegerField(default=10),
        ),
    ]
